name: Linux Compile

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get install cmake ninja-build libbz2-dev
      - name: Build
        run: |
          cmake -H. -Bbuild-cmake -GNinja -DCMAKE_BUILD_TYPE=Release
          cmake --build build-cmake -j
      - name: Create Package
        run: |
          mkdir test-llgl-release
          cp build-cmake/Test-LLGL test-llgl-release/
          cp "$(ldconfig -p | grep libbz2.so.1.0 | tr ' ' '\n' | grep /| head -n1)" test-llgl-release/
      - name: Publish packaged artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-llgl-linux-x64
          path: test-llgl-release
      - name: Test
        continue-on-error: true
        run: |
          cd build-cmake
          ctest -j 
      - name: Echo Test Results
        run: cat build-cmake/Testing/Temporary/LastTest.log