name: Macos Compile

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: brew install cmake ninja xcodes
      - name: Build
        run: |
          cmake -H. -Bbuild-cmake -GNinja -DCMAKE_BUILD_TYPE=Release
          cmake --build build-cmake -j
      - name: Create Package
        run: |
          mkdir test-llgl-release
          cp build-cmake/Test-LLGL test-llgl-release/
      - name: Publish packaged artifacts
        uses: actions/upload-artifact@v4
        with:
            name: test-llgl-mac-bin
            path: test-llgl-release
      - name: Test
        continue-on-error: true
        run: |
          cd build-cmake
          ctest -j 
      - name: Echo Test Results
        run: cat build-cmake/Testing/Temporary/LastTest.log