name: Windows Compile

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
            version: 1.4.309.0
            cache: true
      - name: Build
        run: |
          cmake -S . -B "build/x64" -G "Visual Studio 17 2022" -T v142 -A x64 -DCMAKE_BUILD_TYPE:STRING=Release
          cmake --build ./build/x64
      - name: Publish packaged artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-llgl-windows-x64
          path: build/x64/Debug/Test-LLGL.exe
      - name: Test
        continue-on-error: true
        run: |
          cd build/x64
          ctest -j -C Debug